---
services:
  web:
    build: 
      context: . # to look into current working directory
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app # "." indicates current working directory 
      - /app/node_modules
  # 'docker run -it [image id] npm run test' to run tests on docker container in separate bash terminal
  # '-it' so you can interact and press enter to run tests. 
  tests: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # "." indicates current working directory 
      - /app/node_modules
    command: ["npm", "run", "test"]    
    # 'docker-compose up --build' to run app and test
    # this approach means I don't need to use another bash terminal to run the tests on the active container.
    # I also don't need to get the container id and add it to the run command.
    # The problem is you can't use the test suite with the keyboard shortcuts as could in the above option.
    
